defaults:
  - task_config_base
  - actions:
      - stop
      - move_forward
      - turn_left
      - turn_right
      - look_up
      - look_down
  - measurements:
      - num_steps
      - distance_to_goal
      - success
      - spl
      - soft_spl
      - distance_to_goal_reward
  - lab_sensors:
      - image_goal_rotation_sensor
      - compass_sensor
      - gps_sensor
  - _self_

type: Nav-v0
end_on_success: True
reward_measure: distance_to_goal_reward
success_measure: spl
goal_sensor_uuid: image_goal_rotation
measurements:
  distance_to_goal:
    distance_to: POINT
  success:
    success_distance: 1.0