# @package _global_

defaults:
  - /habitat: habitat_config_base
  - /habitat/task: objectnav
  - /habitat/simulator/agents@habitat.simulator.agents.main_agent: rgb_agent
  - _self_

habitat:
  environment:
    max_episode_steps: 500

  task:
    type: Goat-v1
    actions:
      subtask_stop:
        type: SubtaskStopAction

  simulator:
    turn_angle: 30
    tilt_angle: 30
    action_space_config: "v2"
    agents:
      main_agent:
        sim_sensors:
          rgb_sensor:
            width: 360
            height: 640
            hfov: 42
            position: [0, 1.31, 0]
        height: 1.41
        radius: 0.17
    habitat_sim_v0:
      gpu_device_id: 0
      allow_sliding: False
  
  dataset:
    type: Goat-v1
    split: train
    data_path: data/datasets/goat/v0/{split}/{split}.json.gz
